import type { Metadata } from 'next';
import './globals.css';
import { SideBar } from '@/component/Sidebar/SideBar';
import { Content } from '@/component/Content/Content';
import dayjs from 'dayjs';
import timezone from 'dayjs/plugin/timezone';
import utc from 'dayjs/plugin/utc';
import 'dayjs/locale/fr';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

dayjs.extend(timezone);
dayjs.extend(utc);
dayjs.tz.setDefault('Europe/Paris');
dayjs.locale('fr');

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <main
                    style={{
                        height: '100vh',
                        backgroundColor: 'whitesmoke',
                    }}
                >
                    <SideBar />
                    <Content>{children}</Content>
                </main>
            </body>
        </html>
    );
}
