import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { SideBar } from '@/app/component/Sidebar/SideBar';
import { Content } from '@/app/component/Content/Content';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <main
                    style={{
                        height: '100vh',
                        backgroundColor: 'whitesmoke',
                    }}
                >
                    <SideBar />
                    <Content>{children}</Content>
                </main>
            </body>
        </html>
    );
}
